2024-07-25 12:55:34,898 INFO    Thread-6 (_run_job):246692 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-25 12:55:34,900 INFO    Thread-6 (_run_job):246692 [wandb_setup.py:_flush():76] Configure stats pid to 246692
2024-07-25 12:55:34,900 INFO    Thread-6 (_run_job):246692 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-07-25 12:55:34,900 INFO    Thread-6 (_run_job):246692 [wandb_setup.py:_flush():76] Loading settings from /content/drive/MyDrive/fastMRI_main_TMAttFIVarNet/FastMRI_challenge/wandb/settings
2024-07-25 12:55:34,900 INFO    Thread-6 (_run_job):246692 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'varnet-sweep-test', 'entity': 'superfastmri-seoul-national-university', 'root_dir': '/content/drive/MyDrive/fastMRI_main_TMAttFIVarNet/FastMRI_challenge', 'run_id': 'p7qvj8cz', 'sweep_param_path': '/content/drive/MyDrive/fastMRI_main_TMAttFIVarNet/FastMRI_challenge/wandb/sweep-a690ua88/config-p7qvj8cz.yaml', 'sweep_id': 'a690ua88'}
2024-07-25 12:55:34,900 INFO    Thread-6 (_run_job):246692 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-25 12:55:34,900 INFO    Thread-6 (_run_job):246692 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/content/drive/MyDrive/fastMRI_main_TMAttFIVarNet/FastMRI_challenge/train.py', 'program': '/content/drive/MyDrive/fastMRI_main_TMAttFIVarNet/FastMRI_challenge/train.py'}
2024-07-25 12:55:34,901 INFO    Thread-6 (_run_job):246692 [wandb_init.py:_log_setup():529] Logging user logs to /content/drive/MyDrive/fastMRI_main_TMAttFIVarNet/FastMRI_challenge/wandb/run-20240725_125534-p7qvj8cz/logs/debug.log
2024-07-25 12:55:34,901 INFO    Thread-6 (_run_job):246692 [wandb_init.py:_log_setup():530] Logging internal logs to /content/drive/MyDrive/fastMRI_main_TMAttFIVarNet/FastMRI_challenge/wandb/run-20240725_125534-p7qvj8cz/logs/debug-internal.log
2024-07-25 12:55:34,901 INFO    Thread-6 (_run_job):246692 [wandb_init.py:init():569] calling init triggers
2024-07-25 12:55:34,901 INFO    Thread-6 (_run_job):246692 [wandb_init.py:init():576] wandb.init called with sweep_config: {'cascade': 12, 'chans': 11, 'sens_chans': 5}
config: {}
2024-07-25 12:55:34,901 INFO    Thread-6 (_run_job):246692 [wandb_init.py:init():614] wandb.init() called when a run is still active
2024-07-25 12:55:34,902 ERROR   Thread-6 (_run_job):246692 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 615, in init
    with telemetry.context() as tel:
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 798, in _telemetry_callback
    self._telemetry_flush()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 809, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-07-25 12:55:34,980 INFO    Thread-6 (_run_job):246692 [wandb_run.py:_finish():2107] finishing run superfastmri-seoul-national-university/varnet-sweep-test/3569vk5v
2024-07-25 12:55:40,521 INFO    Thread-8 (_run_job):246692 [wandb_run.py:_finish():2107] finishing run superfastmri-seoul-national-university/varnet-sweep-test/3569vk5v
2024-07-25 12:55:45,956 INFO    Thread-9 (_run_job):246692 [wandb_run.py:_finish():2107] finishing run superfastmri-seoul-national-university/varnet-sweep-test/3569vk5v
2024-07-25 12:55:51,348 INFO    Thread-10 (_run_job):246692 [wandb_run.py:_finish():2107] finishing run superfastmri-seoul-national-university/varnet-sweep-test/3569vk5v
